CREATE DATABASE IF NOT EXISTS cms_project
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE cms_project;

-- =====================
-- COUNTRIES (države)
-- =====================
CREATE TABLE IF NOT EXISTS countries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE
);

INSERT INTO countries (name) VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cape Verde'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Costa Rica'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Eswatini'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('North Korea'),
('North Macedonia'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Korea'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe');


-- =====================
-- USERS
-- =====================
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(60) NOT NULL,
  lastname VARCHAR(60) NOT NULL,
  username VARCHAR(60) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL,
  country_id INT NOT NULL,
  city VARCHAR(80) NOT NULL,
  street VARCHAR(120) NOT NULL,
  dob DATE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('user','editor','admin') DEFAULT 'user',
  approved TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (country_id) REFERENCES countries(id)
);

-- Admin user (username: admin, password: Admin123)
INSERT INTO users (firstname, lastname, username, email, country_id, city, street, dob, password_hash, role, approved)
VALUES ('Filip','Pribanić','admin','admin@cms.local',1,'Zagreb','Ulica 1','2000-01-01','$2y$10$0kbiB7EqugiGLQ7621id9eI1Y39VXWHh40kiRnXvE8u23dx5xY4hu','admin',1);

-- =====================
-- NEWS (vijesti)
-- =====================
CREATE TABLE IF NOT EXISTS news (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_archived TINYINT(1) DEFAULT 0,
  is_approved TINYINT(1) DEFAULT 0,
  author_id INT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS news_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  news_id INT NOT NULL,
  image VARCHAR(255) NOT NULL,
  caption VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE
);

INSERT INTO news (title, image, content, is_archived, is_approved, author_id) VALUES
('Prva vijest','test.jpg','Ovo je sadržaj prve vijesti za CMS projekt.\n\nOdlomak 2.\n\nOdlomak 3.\n\nOdlomak 4.\n\nOdlomak 5.',0,1,1),
('Druga vijest','test.jpg','Ovo je sadržaj druge vijesti za CMS projekt.\n\nOdlomak 2.\n\nOdlomak 3.\n\nOdlomak 4.\n\nOdlomak 5.',0,1,1),
('Treća vijest','test.jpg','Ovo je sadržaj treće vijesti za CMS projekt.\n\nOdlomak 2.\n\nOdlomak 3.\n\nOdlomak 4.\n\nOdlomak 5.',0,1,1),
('Četvrta vijest','test.jpg','Ovo je sadržaj četvrte vijesti za CMS projekt.\n\nOdlomak 2.\n\nOdlomak 3.\n\nOdlomak 4.\n\nOdlomak 5.',0,1,1),
('Peta vijest','test.jpg','Ovo je sadržaj pete vijesti za CMS projekt.\n\nOdlomak 2.\n\nOdlomak 3.\n\nOdlomak 4.\n\nOdlomak 5.',0,1,1);

INSERT INTO news_images (news_id, image, caption) VALUES
(1,'test.jpg','Galerija slika 1'),
(1,'test.jpg','Galerija slika 2'),
(1,'test.jpg','Galerija slika 3');